/*
Copyright 2020 The Krole Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"
	v1alpha1 "ton/pkg/apis/ton/v1alpha1"
	scheme "ton/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LinesGetter has a method to return a LineInterface.
// A group's client should implement this interface.
type LinesGetter interface {
	Lines(namespace string) LineInterface
}

// LineInterface has methods to work with Line resources.
type LineInterface interface {
	Create(ctx context.Context, line *v1alpha1.Line, opts v1.CreateOptions) (*v1alpha1.Line, error)
	Update(ctx context.Context, line *v1alpha1.Line, opts v1.UpdateOptions) (*v1alpha1.Line, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Line, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LineList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Line, err error)
	LineExpansion
}

// lines implements LineInterface
type lines struct {
	client rest.Interface
	ns     string
}

// newLines returns a Lines
func newLines(c *TonV1alpha1Client, namespace string) *lines {
	return &lines{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the line, and returns the corresponding line object, and an error if there is any.
func (c *lines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Line, err error) {
	result = &v1alpha1.Line{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Lines that match those selectors.
func (c *lines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LineList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LineList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested lines.
func (c *lines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("lines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a line and creates it.  Returns the server's representation of the line, and an error, if there is any.
func (c *lines) Create(ctx context.Context, line *v1alpha1.Line, opts v1.CreateOptions) (result *v1alpha1.Line, err error) {
	result = &v1alpha1.Line{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("lines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(line).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a line and updates it. Returns the server's representation of the line, and an error, if there is any.
func (c *lines) Update(ctx context.Context, line *v1alpha1.Line, opts v1.UpdateOptions) (result *v1alpha1.Line, err error) {
	result = &v1alpha1.Line{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lines").
		Name(line.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(line).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the line and deletes it. Returns an error if one occurs.
func (c *lines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lines").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *lines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lines").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched line.
func (c *lines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Line, err error) {
	result = &v1alpha1.Line{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("lines").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
