/*
Copyright 2020 The Krole Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "ton/pkg/apis/ton/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLines implements LineInterface
type FakeLines struct {
	Fake *FakeTonV1alpha1
	ns   string
}

var linesResource = schema.GroupVersionResource{Group: "ton.k8s.io", Version: "v1alpha1", Resource: "lines"}

var linesKind = schema.GroupVersionKind{Group: "ton.k8s.io", Version: "v1alpha1", Kind: "Line"}

// Get takes name of the line, and returns the corresponding line object, and an error if there is any.
func (c *FakeLines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Line, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(linesResource, c.ns, name), &v1alpha1.Line{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Line), err
}

// List takes label and field selectors, and returns the list of Lines that match those selectors.
func (c *FakeLines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(linesResource, linesKind, c.ns, opts), &v1alpha1.LineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LineList{ListMeta: obj.(*v1alpha1.LineList).ListMeta}
	for _, item := range obj.(*v1alpha1.LineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lines.
func (c *FakeLines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(linesResource, c.ns, opts))

}

// Create takes the representation of a line and creates it.  Returns the server's representation of the line, and an error, if there is any.
func (c *FakeLines) Create(ctx context.Context, line *v1alpha1.Line, opts v1.CreateOptions) (result *v1alpha1.Line, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(linesResource, c.ns, line), &v1alpha1.Line{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Line), err
}

// Update takes the representation of a line and updates it. Returns the server's representation of the line, and an error, if there is any.
func (c *FakeLines) Update(ctx context.Context, line *v1alpha1.Line, opts v1.UpdateOptions) (result *v1alpha1.Line, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(linesResource, c.ns, line), &v1alpha1.Line{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Line), err
}

// Delete takes name of the line and deletes it. Returns an error if one occurs.
func (c *FakeLines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(linesResource, c.ns, name), &v1alpha1.Line{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(linesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LineList{})
	return err
}

// Patch applies the patch and returns the patched line.
func (c *FakeLines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Line, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(linesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Line{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Line), err
}
