apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ton-role
rules:
  - apiGroups:
      - ton.k8s.io
    resources:
      - flow
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete